### ISSUE TITLE
how do you test

### ISSUE THREAD

**Issue by shalva97** [DrewCarlson/qBittorrent-Kotlin#2]
There are no test in the project but at least some ```fun main()``` should work right?

I have added a file in Client module called main.kt with main function in it, but green icon doesnot appear. Do you know why?

**Comment by DrewCarlson** [comment]
I use this library in a larger (private) repository that exercises this library.  For now I probably wont work on any tests in this repo, but pull requests are welcome.

That said, I've added a demo module that can be used to explore/test the APIs.  You will see the green run button when viewing this file in Intellij IDEA/Android Studio.
https://github.com/DrewCarlson/qBittorrent-Kotlin/blob/fc7714ad264dc7a525137e8a077d70ceb118d2d9/demo/src/jvmMain/java/main.kt#L6-L12

Example output: `qBittorrent Version: v4.3.1`
