### ISSUE TITLE
Unable to add torrent

### ISSUE THREAD

**Issue by Yash-Garg** [DrewCarlson/qBittorrent-Kotlin#21]
Hey, I am trying to add a torrent using `url` by using the below function.

But it's not adding, other fields are not passed because they are optional as mentioned [here](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-new-torrent).

```kotlin
suspend fun addTorrent(url: String) {
    try {
        client.addTorrent {
            AddTorrentBody(urls = mutableListOf(url))
        }
    } catch (e: Exception) {
        Log.e("addTorrent", e.toString())
    }
}
```

Am I doing something wrong here in the function? I tried passing `mutableListOf(url)` directly also.

**Comment by DrewCarlson** [comment]
Your function should look like this:
```
suspend fun addTorrent(url: String) {
    try {
        client.addTorrent {
            urls.add(url)
        }
    } catch (e: Exception) {
        Log.e("addTorrent", e.toString())
    }
}
```

**Comment by Yash-Garg** [comment]
> Your function should look like this:
> 
> ```
> suspend fun addTorrent(url: String) {
>     try {
>         client.addTorrent {
>             urls.add(url)
>         }
>     } catch (e: Exception) {
>         Log.e("addTorrent", e.toString())
>     }
> }
> ```

Ah, my bad. Thank you!

**Comment by Yash-Garg** [comment]
I had just a quick question, do you plan to add the functionality for uploading torrent file anytime soon?

**Comment by DrewCarlson** [comment]
My use-cases only require magnet links, I was not planning to add file support in the near future.

**Comment by Yash-Garg** [comment]
> My use-cases only require magnet links, I was not planning to add file support in the near future.

Oh, okay!

**Comment by Yash-Garg** [comment]
Hey @DrewCarlson, I am facing a weird issue when adding a torrent using a `https://` link.
It gets added and updates fine on emulator. But when I am trying the same on a physical device, the torrent gets added then the client throws `CancellationException` which shows `java.util.concurrent.CancellationException: Engine failed`.

This doesn't happen on the emulator; do you have any idea why this might be happening?

[Code Reference](https://github.com/Yash-Garg/qBittorrent-KT/blob/develop/app/src/main/kotlin/dev/yashgarg/qbit/ui/server/ServerViewModel.kt#L50-L57)

Thanks!

**Comment by DrewCarlson** [comment]
Thanks for the patch.  Try the latest snapshot and let me know if adding a torrent produces any more errors.  I'll cut a new release in a day or so.

**Comment by Yash-Garg** [comment]
> Thanks for the patch. Try the latest snapshot and let me know if adding a torrent produces any more errors. I'll cut a new release in a day or so.

It works fine now on the latest snapshot.

**Comment by DrewCarlson** [comment]
[v1.0.0-alpha04](https://github.com/DrewCarlson/qBittorrent-Kotlin/releases/tag/v1.0.0-alpha04) is available.

**Comment by Yash-Garg** [comment]
Hey @DrewCarlson, is [this method](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#ban-peers) there in the wrapper?

**Comment by DrewCarlson** [comment]
It's available in the latest snapshot.

**Comment by Yash-Garg** [comment]
> It's available in the latest snapshot.

Thanks!
