### ISSUE TITLE
where are user statistics api calls?

### ISSUE THREAD

**Issue by shalva97** [DrewCarlson/qBittorrent-Kotlin#3]
on Web UI there is this statistics window
![image](https://user-images.githubusercontent.com/22417494/109862654-209dd100-7c7a-11eb-8d0a-6ce9655a831c.png)
I couldnot find anything on qbittorrent wiki page,google doesnot show anything useful and in chromium nothing shows up except jsut the HTML of that window.

so here I am after 2 hours of research and nothing. 

how can I get that values?

**Comment by DrewCarlson** [comment]
https://github.com/qbittorrent/qBittorrent/blob/4259b4571ceb962a778a0bdce803c6e7600e726c/src/webui/www/private/scripts/client.js#L731-L744

Looking at the WebUI source, this panel displays information from the [maindata](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-main-data) syncing endpoint.  With this library, you would collect [`QBittorrentClient.syncMainData()`](https://github.com/DrewCarlson/qBittorrent-Kotlin/blob/5aee0874427b996fc5928fa10942563465215c62/client/src/commonMain/kotlin/QBittorrentClient.kt#L118) and read the relevant fields from [`MainData.serverState`](https://github.com/DrewCarlson/qBittorrent-Kotlin/blob/5aee0874427b996fc5928fa10942563465215c62/models/src/commonMain/kotlin/MainData.kt#L29-L31).

Currently `serverState` is represented as a `JsonObject?` so you'll have to extract each field manually, see the WebUI for field names/types.  A statically typed data model for `serverState` would be appreciated if you'd like contributing one :).
