### ISSUE TITLE
How to pause receiving main data updates?

### ISSUE THREAD

**Issue by HubKing** [DrewCarlson/qBittorrent-Kotlin#61]
Sorry for asking a question here but there is no "Discussions" tab, so I could not think of any better way.

I think it should be necessary to temporarily stop receiving main data updates, in cases like the app becomes invisible (e.g., the user switched to another app). Keep receiving data when the app is not visible is waste of battery.

But how can I stop receiving the data other than maybe destroying the client or logging out? I mean, I thought maybe changing the interval to 0 would stop it, but the interval is a constructor argument that cannot be changed later. I could not find any method like `stopObservingMainData()` or `pauseObservingMainData()`.

**Comment by DrewCarlson** [comment]
No problem, this is a fine place to ask questions but I will open the discussions section.

To end mainData polling, it is only required that you cancel all Flows that are collecting `observeMainData()` and `observeTorrent(...)`.  When these Flows are not being collected, all polling behavior will stop and the client is idle until you invoke another endpoint or begin collecting one of those Flows again.

I considered this behavior from a mobile perspective in which it is common to use CoroutineScope's that are bound to the foreground/background lifecycle of an application.  If there is some reason this would not work for your use-case it would be great to hear more about it.

**Comment by DrewCarlson** [comment]
You may find Android's '[Use Kotlin coroutines with lifecycle-aware components](https://developer.android.com/topic/libraries/architecture/coroutines)' documentation helpful.
