### ISSUE TITLE
How to know which torrents are updated in the main data?

### ISSUE THREAD

**Issue by HubKing** [DrewCarlson/qBittorrent-Kotlin#62]
If I remember correctly, the original "Get main data" API returns only the torrents that have been updated since last call, unless "full_update" is true. But with 

```
client.observeTorrent("c12fe1c06bba254a9dc9f519b335aa7c1367a88a")
    .collect { data ->
    }
```

`data.torrents` seems to contain all torrents always.  How can I which torrents have been updated since the last call?

**Comment by DrewCarlson** [comment]
So using `client.observeTorrent(...)` will only give you details about a single torrent, currently it will emit the same `Torrent` every time the `MainData` is updated regardless of if the torrent is changed or not.  You can avoid this behavior by doing `client.observeTorrent(...).distinctUntilChanged()` which will only emit the `Torrent` when it has actually changed.  For the `observeTorrent(...)` function, I believe the `distinctUntilChanged()` operator should be added in this library so this behavior is the default.

With `observeMainData()` it is convenient behavior from an application development perspective to take each patch and keep applying it to the existing data and emit the whole model with each update.  This allows for greater flexibility when dealing with the data in terms of a `Flow`.  To that end, you can easily produce a list of torrents that have changed with something like:

```kotlin
    client.observeMainData()
        .map { it.torrents }
        .run {
            var previousTorrents = emptySet<Torrent>()
            transform { newTorrentsMap ->
                val nextTorrents = newTorrentsMap.values.toSet()
                emit(nextTorrents - previousTorrents)
                previousTorrents = nextTorrents
            }
        }
        .distinctUntilChanged()
        .onEach { torrents ->
            println("Changed torrents: ${torrents.joinToString { it.hash }}")
        }
```

**Comment by HubKing** [comment]
I must first admit that I don't know much about this Flow thing or the React thing, so what I am saying from now on may well be stupid, but I feel like this would be complex, unless it is continuous observation. But on Android, maybe there can be a time when it is not necessary to update the visual representation of the torrent list, and the `observerMainData` maybe keeping getting data from the server in the background (I don't know if it pauses itself or how to pause). To save a copy of the whole torrent set and save it somewhere seems a lot of memory.

Internally, there is one whole torrent map and this library is keep updating it, even if this code is used and it only emits changed ones, right? If so, I wonder what if each `Torrent` had  some sort of field that denotes the rid that it was last updated at, and when the library updates some torrents in the internal whole map, it update their rid field. It is just an integer, so it won't take a lot of memory, and it won't take a lot of CPU to update it.

Then, all I have to do would be saving the single integer `rid` somewhere at any arbitrarily main update, and at any future main update, I could just filter the list of torrents that have a bigger `rid` than the saved `rid`

```
    //save the rid before pausing update
     viewData.lastRid = mainData.rid;

    //... and later when resuming update
     val updatedTorrents = mainData.torrents.filter {it.rid > lastRid };

```
If the `rid` of `Torrent` is hidden from the user, the library could have a convenience method like

     val updatedTorrents = mainData.getChangedTorrentsSince(lastRid);

and the library would internally filter the torrents and return new ones since then.

**Comment by DrewCarlson** [comment]
Sorry I'm not quite understanding which part is giving you concerns about CPU time and memory usage.

Every time `observeMainData(): Flow<MainData>` emits a new `MainData` instance, you're getting a copy of the previous instance with only the updated fields changed as the server only responds with a partial JSON object.  So yes the current instance of `MainData` is retained internally but it's being efficiently copied and updated with each server response.  We aren't talking about a lot of memory or CPU time here unless your qBittorrent instance has well over 1000 torrents, even on a low-end Android device.

> But on Android, maybe there can be a time when it is not necessary to update the visual representation of the torrent list, and the observerMainData maybe keeping getting data from the server in the background (I don't know if it pauses itself or how to pause).

This is an Android detail that can be handled in combination with a proper `CoroutineScope`.  In your UI component, such as an Activity, you can collect `observeMainData()` into a special `CoroutineScope` which stops collecting (and pauses the MainData polling) when the app is backgrounded.  There are utilities to handle joining `Flow` cancellation with Android lifecycle signals, you could do something like:
```Kotlin
class TorrentActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        lifecycleScope.launch {
            repeatOnLifecycle(Lifecycle.State.RESUMED) {
                client.observeMainData().collect { mainData ->
                    println(mainData)
                }
            }
        }
    }
}
```
In this example, the `client.observeMainData()` `Flow` is cancelled and polling stops every time the app enters the background (`PAUSED`) and resumes again when it enters the foreground (`RESUMED`).  If you put this together with my previous snippet to produce a list of changed torrents, you are still not dealing with all that much CPU and memory overhead.

**Comment by HubKing** [comment]
I guess you are right.
